# Generated by Django 5.2.3 on 2025-07-02 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Text')),
                ('field_type', models.CharField(choices=[('SL', 'Select'), ('RS', 'Radio Select'), ('CB', 'Check Box'), ('NI', 'Number Input'), ('TA', 'Text Area'), ('TI', 'Text Input')], max_length=2, verbose_name='Type')),
                ('required', models.BooleanField(verbose_name='Required')),
                ('min_value', models.IntegerField(verbose_name='Min value')),
                ('max_value', models.IntegerField(verbose_name='Max value')),
                ('max_length', models.IntegerField(verbose_name='Max Length')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.survey', verbose_name='Survey'),
        ),
    ]
