# Generated by Django 5.2.3 on 2025-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_length',
            field=models.IntegerField(blank=True, verbose_name='Max Length'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_value',
            field=models.IntegerField(blank=True, verbose_name='Max value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_value',
            field=models.IntegerField(blank=True, verbose_name='Min value'),
        ),
    ]
