# Generated by Django 5.2.4 on 2025-07-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_question_max_length_alter_question_max_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_length',
            field=models.IntegerField(default=255, verbose_name='Max Length'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_value',
            field=models.IntegerField(default=255, verbose_name='Max value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_value',
            field=models.IntegerField(default=0, verbose_name='Min value'),
        ),
    ]
