# Generated by Django 5.2.4 on 2025-07-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_answer_index_question_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField()),
                ('value', models.CharField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.survey')),
            ],
        ),
    ]
