# Generated by Django 5.2.4 on 2025-07-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_length',
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('SL', 'Select'), ('RS', 'Radio Select'), ('CB', 'Check Box'), ('NI', 'Number Input')], max_length=2, verbose_name='Type'),
        ),
    ]
