# Generated by Django 5.2.4 on 2025-07-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_answer_index_remove_question_max_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.RemoveField(
            model_name='data',
            name='key',
        ),
        migrations.AddField(
            model_name='data',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.answer'),
        ),
    ]
