# Generated by Django 5.2.4 on 2025-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_answer_value_remove_data_key_data_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
