# Generated by Django 5.2.4 on 2025-07-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
