# Generated by Django 5.2.4 on 2025-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_remove_data_survey_remove_data_value_data_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
