# Generated by Django 5.2.4 on 2025-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_data_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='required',
        ),
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
