# Generated by Django 5.2.4 on 2025-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_remove_question_required_alter_data_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='open',
            field=models.BooleanField(default=False, verbose_name='Open'),
            preserve_default=False,
        ),
    ]
