# Generated by Django 5.2.4 on 2025-07-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_survey_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.IntegerField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='data',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question', verbose_name='Question'),
        ),
    ]
