# Generated by Django 5.0.6 on 2024-08-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='admin@restaurant.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.TextField(default='person', max_length=128),
            preserve_default=False,
        ),
    ]
