# Generated by Django 5.0.6 on 2024-10-08 09:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_review_options_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=255)),
                ('topic_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=255)),
                ('prediction', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.TextField(max_length=255)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.answer')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
