# Generated by Django 5.0.6 on 2024-10-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.IntegerField(choices=[('1', 'user_satisfaction'), ('2', 'opening_hours'), ('3', 'address'), ('4', 'contact'), ('5', 'menu'), ('6', 'reservation'), ('7', 'home_delivery'), ('8', 'services'), ('9', 'thanks_answer'), ('10', 'positive_review'), ('11', 'negative_review')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
