# Generated by Django 5.0.6 on 2024-10-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_answer_topic_id_answer_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
