# Generated by Django 5.0.6 on 2024-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_review_prediction_review_sentiment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sentiment',
            new_name='i_like',
        ),
        migrations.AlterField(
            model_name='answer',
            name='topic',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'user_satisfaction'), (2, 'opening_hours'), (3, 'address'), (4, 'contact'), (5, 'menu'), (6, 'reservation'), (7, 'home_delivery'), (8, 'services'), (9, 'thanks_answer'), (10, 'positive_review'), (11, 'negative_review')]),
        ),
    ]
