# Generated by Django 5.0.6 on 2024-10-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_rename_sentiment_review_i_like_alter_answer_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='i_like',
            new_name='sentiment',
        ),
    ]
