# Generated by Django 5.0.6 on 2024-10-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_rename_i_like_review_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='topic',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'user_satisfaction'), (2, 'opening_hours'), (3, 'address'), (4, 'contact'), (5, 'menu'), (6, 'reservation'), (7, 'home_delivery'), (8, 'services'), (9, 'thanks_answer'), (10, 'positive_review'), (11, 'negative_review'), (12, 'alergens'), (13, 'pets'), (14, 'dressing'), (15, 'children'), (16, 'smoking'), (17, 'parking'), (18, 'disability')]),
        ),
    ]
