# Generated by Django 5.0.6 on 2024-08-18 09:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='images/categories')),
                ('priority', models.IntegerField(blank=True)),
                ('parent_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bazaar.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('mail', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Allowed')], default=0)),
                ('picture_0', models.ImageField(blank=True, upload_to='images/')),
                ('picture_1', models.ImageField(blank=True, upload_to='images/')),
                ('picture_2', models.ImageField(blank=True, upload_to='images/')),
                ('picture_3', models.ImageField(blank=True, upload_to='images/')),
                ('picture_4', models.ImageField(blank=True, upload_to='images/')),
                ('picture_5', models.ImageField(blank=True, upload_to='images/')),
                ('picture_6', models.ImageField(blank=True, upload_to='images/')),
                ('picture_7', models.ImageField(blank=True, upload_to='images/')),
                ('picture_8', models.ImageField(blank=True, upload_to='images/')),
                ('picture_9', models.ImageField(blank=True, upload_to='images/')),
                ('rank', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.category')),
                ('alternative_currencies', models.ManyToManyField(blank=True, related_name='alternative_currencies', to='bazaar.currency')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.currency')),
            ],
            options={
                'ordering': ['-rank', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(0, 'Forbidden'), (1, 'Offensive'), (2, 'Scam'), (3, 'Wrong Category'), (4, 'Joke'), (5, 'Other Reason')])),
                ('description', models.CharField(blank=True, max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('readed', models.BooleanField(default=False)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazaar.ad')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-reason'],
            },
        ),
    ]
