# Generated by Django 5.0.6 on 2024-08-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_alter_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories'),
        ),
    ]
