# Generated by Django 5.0.6 on 2024-09-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0005_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-priority'], 'verbose_name_plural': 'categories'},
        ),
    ]
