# Generated by Django 5.1.2 on 2024-11-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='phone',
        ),
    ]
