# Generated by Django 5.1.3 on 2024-11-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_ad_owner_alter_ad_moderator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-rank', '-date'], 'permissions': [('modetate_ad', 'Can moderate an Ad')]},
        ),
    ]
