# Generated by Django 5.1.3 on 2024-11-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0010_alter_ad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-rank', '-date'], 'permissions': [('moderate_ad', 'Can moderate an Ad')]},
        ),
    ]
