# Generated by Django 5.1.4 on 2024-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0012_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
