# Generated by Django 5.1.4 on 2025-01-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0013_alter_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
