# Generated by Django 5.1.4 on 2025-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0014_ad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
