# Generated by Django 5.1.6 on 2025-02-20 09:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0015_category_slug_currency_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='default_description', max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='alternative_currencies',
            field=models.ManyToManyField(blank=True, related_name='alternative_currencies', to='bazaar.currency', verbose_name='alternative currencies'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=4096, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='moderator'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_0',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_1',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_3',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_4',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_5',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_6',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_7',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_8',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture_9',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Allowed')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bazaar.category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=4, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=64, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazaar.ad', verbose_name='ad'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=254, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='moderator'),
        ),
        migrations.AlterField(
            model_name='report',
            name='readed',
            field=models.BooleanField(default=False, verbose_name='readed'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Forbidden'), (1, 'Offensive'), (2, 'Scam'), (3, 'Wrong Category'), (4, 'Joke'), (5, 'Other Reason')], verbose_name='reason'),
        ),
    ]
