# Generated by Django 5.1.6 on 2025-03-12 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0016_category_description_alter_ad_alternative_currencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad '), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='rating')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'reviewed'), name='unique_review')],
            },
        ),
    ]
