# Generated by Django 5.1.7 on 2025-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0017_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': [models.F('owner__profile'), '-date'], 'permissions': [('moderate_ad', 'Can moderate an Ad')]},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': [models.OrderBy(models.F('get_score'), descending=True)]},
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
