# Generated by Django 5.2.3 on 2025-07-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0019_alter_review_reviewed_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-date'], 'permissions': [('moderate_ad', 'Can moderate an Ad')]},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='rating'),
        ),
    ]
