on: [push]
jobs:
  Deploy-my-code-on-AWS-Lighsail-VPS:
    runs-on: self-hosted
    steps:
      - run: echo 'Deploying the project'
      # Stop Nginx and Gunicorn servers
      - run: git pull https://arielb0:$GITHUB_TOKEN@github.com/arielb0/portfolio.git
      # Start Nginx and Gunicorn servers
      - run: echo 'Proyect deployed successfully.'
