on: [push]
jobs:
  Deploy-my-code-on-AWS-Lighsail-VPS:
    runs-on: self-hosted
    steps:
      - run: |
          REPO_URL=https://arielb0:$GITHUB_TOKEN@github.com/arielb0/portfolio.git
          VENV_PATH=./portfolio/venv
          
          echo 'Deploying the project'
          sudo systemctl stop nginx
          sudo systemctl stop gunicorn
          
          if [ -d "./portfolio/.git" ]; then
            echo "Executing git pull"
            git pull $REPO_URL
          else
            echo "Executing git clone"
            git clone $REPO_URL
          fi
          
          python3 -m venv $VENV_PATH
          source $VENV_PATH/bin/activate

          pip install -r ./portfolio/requirements.txt

          sudo systemctl start nginx
          sudo systemctl start gunicorn

          echo 'Proyect deployed successfully.'
