on: [push]
jobs:
  Deploy-my-code-on-AWS-Lighsail-VPS:
    runs-on: self-hosted
    steps:
      - run: |
          REPO_URL=https://arielb0:$GITHUB_TOKEN@github.com/arielb0/portfolio.git
          VENV_PATH=${GITHUB_WORKSPACE}/venv
          
          echo 'Deploying the project'
          sudo systemctl stop nginx
          sudo systemctl stop gunicorn
          
          if [-d "$GITHUB_WORKSPACE]/.git"]; then
            echo "Executing git pull"
            git pull REPO_URL
          else
            echo "Executing git clone"
            git clone REPO_URL

          
          python -m venv $VENV_PATH
          source $VENV_PATH/bin/activate

          pip install -r ${GITHUB_WORKSPACE}/requirements.txt

          sudo systemctl start nginx
          sudo systemctl start gunicorn

          echo 'Proyect deployed successfully.'
